name: jaineel_portfolio
description: "Jaineel's Portfolio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  material_design_icons_flutter: ^7.0.7296
  eva_icons_flutter: ^3.1.0
  provider: ^6.1.2
  url_launcher: ^6.2.5
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - res/icons/
    - res/images/

  fonts:
    - family: Inter
      fonts:
        - asset: res/fonts/Inter-Thin.ttf
          weight: 100
        - asset: res/fonts/Inter-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: res/fonts/Inter-Light.ttf
          weight: 300
        - asset: res/fonts/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/Inter-Regular.ttf
          weight: 400
        - asset: res/fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/Inter-Medium.ttf
          weight: 500
        - asset: res/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: res/fonts/Inter-Bold.ttf
          weight: 700
        - asset: res/fonts/Inter-BoldItalic.ttf
          style: italic
          weight: 700
